# This is a basic workflow to help you get started with Actions

name: Deploy to Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploying to Github Pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Authorizing Github action
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
        uses: oleksiyrudenko/gha-git-credentials@v1

      - name: Doploy to GitHub Pages
        uses: amitsingh-007/deploy-to-github-pages@v1.1